apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-demo
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
        - name: docker-demo
          image: aug12018/dockerdemo:latest
          ports:
            - containerPort: 80 # This refers to the port number on which the application inside the container listens for traffic. 
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
